// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: eganow/api/merchant/common_service.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_MerchantCommonSvc_GetActiveRegulators_0(ctx context.Context, marshaler runtime.Marshaler, client MerchantCommonSvcClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq MerchantEmpty
	var metadata runtime.ServerMetadata

	msg, err := client.GetActiveRegulators(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_MerchantCommonSvc_GetActiveRegulators_0(ctx context.Context, marshaler runtime.Marshaler, server MerchantCommonSvcServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq MerchantEmpty
	var metadata runtime.ServerMetadata

	msg, err := server.GetActiveRegulators(ctx, &protoReq)
	return msg, metadata, err

}

func request_MerchantCommonSvc_GetActiveIndustries_0(ctx context.Context, marshaler runtime.Marshaler, client MerchantCommonSvcClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq MerchantEmpty
	var metadata runtime.ServerMetadata

	msg, err := client.GetActiveIndustries(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_MerchantCommonSvc_GetActiveIndustries_0(ctx context.Context, marshaler runtime.Marshaler, server MerchantCommonSvcServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq MerchantEmpty
	var metadata runtime.ServerMetadata

	msg, err := server.GetActiveIndustries(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterMerchantCommonSvcHandlerServer registers the http handlers for service MerchantCommonSvc to "mux".
// UnaryRPC     :call MerchantCommonSvcServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMerchantCommonSvcHandlerFromEndpoint instead.
func RegisterMerchantCommonSvcHandlerServer(ctx context.Context, mux *runtime.ServeMux, server MerchantCommonSvcServer) error {

	mux.Handle("GET", pattern_MerchantCommonSvc_GetActiveRegulators_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/eganow.api.merchant.MerchantCommonSvc/GetActiveRegulators", runtime.WithHTTPPathPattern("/api/v1/merchants/common/regulators"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_MerchantCommonSvc_GetActiveRegulators_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MerchantCommonSvc_GetActiveRegulators_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_MerchantCommonSvc_GetActiveIndustries_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/eganow.api.merchant.MerchantCommonSvc/GetActiveIndustries", runtime.WithHTTPPathPattern("/api/v1/merchants/common/industries"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_MerchantCommonSvc_GetActiveIndustries_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MerchantCommonSvc_GetActiveIndustries_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterMerchantCommonSvcHandlerFromEndpoint is same as RegisterMerchantCommonSvcHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMerchantCommonSvcHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterMerchantCommonSvcHandler(ctx, mux, conn)
}

// RegisterMerchantCommonSvcHandler registers the http handlers for service MerchantCommonSvc to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMerchantCommonSvcHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterMerchantCommonSvcHandlerClient(ctx, mux, NewMerchantCommonSvcClient(conn))
}

// RegisterMerchantCommonSvcHandlerClient registers the http handlers for service MerchantCommonSvc
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MerchantCommonSvcClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MerchantCommonSvcClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MerchantCommonSvcClient" to call the correct interceptors.
func RegisterMerchantCommonSvcHandlerClient(ctx context.Context, mux *runtime.ServeMux, client MerchantCommonSvcClient) error {

	mux.Handle("GET", pattern_MerchantCommonSvc_GetActiveRegulators_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/eganow.api.merchant.MerchantCommonSvc/GetActiveRegulators", runtime.WithHTTPPathPattern("/api/v1/merchants/common/regulators"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_MerchantCommonSvc_GetActiveRegulators_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MerchantCommonSvc_GetActiveRegulators_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_MerchantCommonSvc_GetActiveIndustries_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/eganow.api.merchant.MerchantCommonSvc/GetActiveIndustries", runtime.WithHTTPPathPattern("/api/v1/merchants/common/industries"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_MerchantCommonSvc_GetActiveIndustries_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MerchantCommonSvc_GetActiveIndustries_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_MerchantCommonSvc_GetActiveRegulators_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "merchants", "common", "regulators"}, ""))

	pattern_MerchantCommonSvc_GetActiveIndustries_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "merchants", "common", "industries"}, ""))
)

var (
	forward_MerchantCommonSvc_GetActiveRegulators_0 = runtime.ForwardResponseMessage

	forward_MerchantCommonSvc_GetActiveIndustries_0 = runtime.ForwardResponseMessage
)
