// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: eganow/api/common/common_data_entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupValue int32

const (
	GroupValue_GROUP_VALUE_UNKNOWN  GroupValue = 0
	GroupValue_GROUP_VALUE_PERSONAL GroupValue = 1
	GroupValue_GROUP_VALUE_BUSINESS GroupValue = 2
)

// Enum value maps for GroupValue.
var (
	GroupValue_name = map[int32]string{
		0: "GROUP_VALUE_UNKNOWN",
		1: "GROUP_VALUE_PERSONAL",
		2: "GROUP_VALUE_BUSINESS",
	}
	GroupValue_value = map[string]int32{
		"GROUP_VALUE_UNKNOWN":  0,
		"GROUP_VALUE_PERSONAL": 1,
		"GROUP_VALUE_BUSINESS": 2,
	}
)

func (x GroupValue) Enum() *GroupValue {
	p := new(GroupValue)
	*p = x
	return p
}

func (x GroupValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupValue) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_common_common_data_entity_proto_enumTypes[0].Descriptor()
}

func (GroupValue) Type() protoreflect.EnumType {
	return &file_eganow_api_common_common_data_entity_proto_enumTypes[0]
}

func (x GroupValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupValue.Descriptor instead.
func (GroupValue) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_common_common_data_entity_proto_rawDescGZIP(), []int{0}
}

// AccountLocationValue is used to define the location of the account (required for new customer registration)
type AccountLocationValue int32

const (
	AccountLocationValue_ACCOUNT_LOCATION_UNKNOWN  AccountLocationValue = 0
	AccountLocationValue_ACCOUNT_LOCATION_INTERNAL AccountLocationValue = 1
	AccountLocationValue_ACCOUNT_LOCATION_EXTERNAL AccountLocationValue = 2
)

// Enum value maps for AccountLocationValue.
var (
	AccountLocationValue_name = map[int32]string{
		0: "ACCOUNT_LOCATION_UNKNOWN",
		1: "ACCOUNT_LOCATION_INTERNAL",
		2: "ACCOUNT_LOCATION_EXTERNAL",
	}
	AccountLocationValue_value = map[string]int32{
		"ACCOUNT_LOCATION_UNKNOWN":  0,
		"ACCOUNT_LOCATION_INTERNAL": 1,
		"ACCOUNT_LOCATION_EXTERNAL": 2,
	}
)

func (x AccountLocationValue) Enum() *AccountLocationValue {
	p := new(AccountLocationValue)
	*p = x
	return p
}

func (x AccountLocationValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountLocationValue) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_common_common_data_entity_proto_enumTypes[1].Descriptor()
}

func (AccountLocationValue) Type() protoreflect.EnumType {
	return &file_eganow_api_common_common_data_entity_proto_enumTypes[1]
}

func (x AccountLocationValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountLocationValue.Descriptor instead.
func (AccountLocationValue) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_common_common_data_entity_proto_rawDescGZIP(), []int{1}
}

type ClientPlatform int32

const (
	ClientPlatform_CLIENT_UNKNOWN ClientPlatform = 0
	ClientPlatform_CLIENT_MOBILE  ClientPlatform = 1
	ClientPlatform_CLIENT_WEB     ClientPlatform = 2
	ClientPlatform_CLIENT_API     ClientPlatform = 3
)

// Enum value maps for ClientPlatform.
var (
	ClientPlatform_name = map[int32]string{
		0: "CLIENT_UNKNOWN",
		1: "CLIENT_MOBILE",
		2: "CLIENT_WEB",
		3: "CLIENT_API",
	}
	ClientPlatform_value = map[string]int32{
		"CLIENT_UNKNOWN": 0,
		"CLIENT_MOBILE":  1,
		"CLIENT_WEB":     2,
		"CLIENT_API":     3,
	}
)

func (x ClientPlatform) Enum() *ClientPlatform {
	p := new(ClientPlatform)
	*p = x
	return p
}

func (x ClientPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_common_common_data_entity_proto_enumTypes[2].Descriptor()
}

func (ClientPlatform) Type() protoreflect.EnumType {
	return &file_eganow_api_common_common_data_entity_proto_enumTypes[2]
}

func (x ClientPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientPlatform.Descriptor instead.
func (ClientPlatform) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_common_common_data_entity_proto_rawDescGZIP(), []int{2}
}

type UserAccountStatus int32

const (
	UserAccountStatus_USER_ACCOUNT_STATUS_UNKNOWN UserAccountStatus = 0
	UserAccountStatus_USER_ACCOUNT_STATUS_ACTIVE  UserAccountStatus = 1
	UserAccountStatus_USER_ACCOUNT_STATUS_BLOCKED UserAccountStatus = 2
)

// Enum value maps for UserAccountStatus.
var (
	UserAccountStatus_name = map[int32]string{
		0: "USER_ACCOUNT_STATUS_UNKNOWN",
		1: "USER_ACCOUNT_STATUS_ACTIVE",
		2: "USER_ACCOUNT_STATUS_BLOCKED",
	}
	UserAccountStatus_value = map[string]int32{
		"USER_ACCOUNT_STATUS_UNKNOWN": 0,
		"USER_ACCOUNT_STATUS_ACTIVE":  1,
		"USER_ACCOUNT_STATUS_BLOCKED": 2,
	}
)

func (x UserAccountStatus) Enum() *UserAccountStatus {
	p := new(UserAccountStatus)
	*p = x
	return p
}

func (x UserAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_common_common_data_entity_proto_enumTypes[3].Descriptor()
}

func (UserAccountStatus) Type() protoreflect.EnumType {
	return &file_eganow_api_common_common_data_entity_proto_enumTypes[3]
}

func (x UserAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAccountStatus.Descriptor instead.
func (UserAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_common_common_data_entity_proto_rawDescGZIP(), []int{3}
}

type UserPasswordStatus int32

const (
	UserPasswordStatus_PASSWORD_RESET_STATUS_UNKNOWN   UserPasswordStatus = 0
	UserPasswordStatus_PASSWORD_RESET_STATUS_TEMPORAL  UserPasswordStatus = 1
	UserPasswordStatus_PASSWORD_RESET_STATUS_PERMANENT UserPasswordStatus = 2
)

// Enum value maps for UserPasswordStatus.
var (
	UserPasswordStatus_name = map[int32]string{
		0: "PASSWORD_RESET_STATUS_UNKNOWN",
		1: "PASSWORD_RESET_STATUS_TEMPORAL",
		2: "PASSWORD_RESET_STATUS_PERMANENT",
	}
	UserPasswordStatus_value = map[string]int32{
		"PASSWORD_RESET_STATUS_UNKNOWN":   0,
		"PASSWORD_RESET_STATUS_TEMPORAL":  1,
		"PASSWORD_RESET_STATUS_PERMANENT": 2,
	}
)

func (x UserPasswordStatus) Enum() *UserPasswordStatus {
	p := new(UserPasswordStatus)
	*p = x
	return p
}

func (x UserPasswordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserPasswordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_common_common_data_entity_proto_enumTypes[4].Descriptor()
}

func (UserPasswordStatus) Type() protoreflect.EnumType {
	return &file_eganow_api_common_common_data_entity_proto_enumTypes[4]
}

func (x UserPasswordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserPasswordStatus.Descriptor instead.
func (UserPasswordStatus) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_common_common_data_entity_proto_rawDescGZIP(), []int{4}
}

type CountryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName     string `protobuf:"bytes,1,opt,name=CountryName,proto3" json:"CountryName,omitempty"`
	CountryCode     string `protobuf:"bytes,2,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	CountryDialCode string `protobuf:"bytes,3,opt,name=CountryDialCode,proto3" json:"CountryDialCode,omitempty"`
	CurrencyIso     string `protobuf:"bytes,4,opt,name=CurrencyIso,proto3" json:"CurrencyIso,omitempty"`
	CountryFlagUrl  string `protobuf:"bytes,5,opt,name=CountryFlagUrl,proto3" json:"CountryFlagUrl,omitempty"`
	MobileNoMinLen  int32  `protobuf:"varint,6,opt,name=MobileNoMinLen,proto3" json:"MobileNoMinLen,omitempty"`
	MobileNoMaxLen  int32  `protobuf:"varint,7,opt,name=MobileNoMaxLen,proto3" json:"MobileNoMaxLen,omitempty"`
}

func (x *CountryData) Reset() {
	*x = CountryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eganow_api_common_common_data_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryData) ProtoMessage() {}

func (x *CountryData) ProtoReflect() protoreflect.Message {
	mi := &file_eganow_api_common_common_data_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryData.ProtoReflect.Descriptor instead.
func (*CountryData) Descriptor() ([]byte, []int) {
	return file_eganow_api_common_common_data_entity_proto_rawDescGZIP(), []int{0}
}

func (x *CountryData) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *CountryData) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CountryData) GetCountryDialCode() string {
	if x != nil {
		return x.CountryDialCode
	}
	return ""
}

func (x *CountryData) GetCurrencyIso() string {
	if x != nil {
		return x.CurrencyIso
	}
	return ""
}

func (x *CountryData) GetCountryFlagUrl() string {
	if x != nil {
		return x.CountryFlagUrl
	}
	return ""
}

func (x *CountryData) GetMobileNoMinLen() int32 {
	if x != nil {
		return x.MobileNoMinLen
	}
	return 0
}

func (x *CountryData) GetMobileNoMaxLen() int32 {
	if x != nil {
		return x.MobileNoMaxLen
	}
	return 0
}

var File_eganow_api_common_common_data_entity_proto protoreflect.FileDescriptor

var file_eganow_api_common_common_data_entity_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x65, 0x67,
	0x61, 0x6e, 0x6f, 0x77, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22,
	0x95, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x69,
	0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x73, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x73, 0x6f, 0x12,
	0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x6c, 0x61, 0x67, 0x55, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x46, 0x6c, 0x61, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x4e, 0x6f, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x6f, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x12,
	0x26, 0x0a, 0x0e, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x6f, 0x4d, 0x61, 0x78, 0x4c, 0x65,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e,
	0x6f, 0x4d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x2a, 0x59, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x56,
	0x41, 0x4c, 0x55, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x14, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x50, 0x45,
	0x52, 0x53, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x42, 0x55, 0x53, 0x49, 0x4e, 0x45, 0x53, 0x53,
	0x10, 0x02, 0x2a, 0x72, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x43, 0x43, 0x4f,
	0x55, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x58, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x10, 0x02, 0x2a, 0x57, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4c, 0x49, 0x45,
	0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x57, 0x45, 0x42, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x03, 0x2a,
	0x75, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x43, 0x43,
	0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54,
	0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x4c, 0x4f,
	0x43, 0x4b, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x80, 0x01, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a,
	0x1d, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x22, 0x0a, 0x1e, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x52, 0x45, 0x53,
	0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x4f, 0x52,
	0x41, 0x4c, 0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44,
	0x5f, 0x52, 0x45, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45,
	0x52, 0x4d, 0x41, 0x4e, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_eganow_api_common_common_data_entity_proto_rawDescOnce sync.Once
	file_eganow_api_common_common_data_entity_proto_rawDescData = file_eganow_api_common_common_data_entity_proto_rawDesc
)

func file_eganow_api_common_common_data_entity_proto_rawDescGZIP() []byte {
	file_eganow_api_common_common_data_entity_proto_rawDescOnce.Do(func() {
		file_eganow_api_common_common_data_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_eganow_api_common_common_data_entity_proto_rawDescData)
	})
	return file_eganow_api_common_common_data_entity_proto_rawDescData
}

var file_eganow_api_common_common_data_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_eganow_api_common_common_data_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_eganow_api_common_common_data_entity_proto_goTypes = []interface{}{
	(GroupValue)(0),           // 0: eganow.api.common.GroupValue
	(AccountLocationValue)(0), // 1: eganow.api.common.AccountLocationValue
	(ClientPlatform)(0),       // 2: eganow.api.common.ClientPlatform
	(UserAccountStatus)(0),    // 3: eganow.api.common.UserAccountStatus
	(UserPasswordStatus)(0),   // 4: eganow.api.common.UserPasswordStatus
	(*CountryData)(nil),       // 5: eganow.api.common.CountryData
}
var file_eganow_api_common_common_data_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eganow_api_common_common_data_entity_proto_init() }
func file_eganow_api_common_common_data_entity_proto_init() {
	if File_eganow_api_common_common_data_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eganow_api_common_common_data_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eganow_api_common_common_data_entity_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eganow_api_common_common_data_entity_proto_goTypes,
		DependencyIndexes: file_eganow_api_common_common_data_entity_proto_depIdxs,
		EnumInfos:         file_eganow_api_common_common_data_entity_proto_enumTypes,
		MessageInfos:      file_eganow_api_common_common_data_entity_proto_msgTypes,
	}.Build()
	File_eganow_api_common_common_data_entity_proto = out.File
	file_eganow_api_common_common_data_entity_proto_rawDesc = nil
	file_eganow_api_common_common_data_entity_proto_goTypes = nil
	file_eganow_api_common_common_data_entity_proto_depIdxs = nil
}
