// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: eganow/api/billpay/data_purchase_entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // bundle id
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // name e.g. "1GB Social Data"
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"` // amount in GHS
}

func (x *DataBundle) Reset() {
	*x = DataBundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eganow_api_billpay_data_purchase_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBundle) ProtoMessage() {}

func (x *DataBundle) ProtoReflect() protoreflect.Message {
	mi := &file_eganow_api_billpay_data_purchase_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBundle.ProtoReflect.Descriptor instead.
func (*DataBundle) Descriptor() ([]byte, []int) {
	return file_eganow_api_billpay_data_purchase_entity_proto_rawDescGZIP(), []int{0}
}

func (x *DataBundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataBundle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataBundle) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_eganow_api_billpay_data_purchase_entity_proto protoreflect.FileDescriptor

var file_eganow_api_billpay_data_purchase_entity_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6c,
	0x6c, 0x70, 0x61, 0x79, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x6c, 0x6c,
	0x70, 0x61, 0x79, 0x22, 0x48, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x23, 0x5a,
	0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x67, 0x61, 0x6e,
	0x6f, 0x77, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eganow_api_billpay_data_purchase_entity_proto_rawDescOnce sync.Once
	file_eganow_api_billpay_data_purchase_entity_proto_rawDescData = file_eganow_api_billpay_data_purchase_entity_proto_rawDesc
)

func file_eganow_api_billpay_data_purchase_entity_proto_rawDescGZIP() []byte {
	file_eganow_api_billpay_data_purchase_entity_proto_rawDescOnce.Do(func() {
		file_eganow_api_billpay_data_purchase_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_eganow_api_billpay_data_purchase_entity_proto_rawDescData)
	})
	return file_eganow_api_billpay_data_purchase_entity_proto_rawDescData
}

var file_eganow_api_billpay_data_purchase_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_eganow_api_billpay_data_purchase_entity_proto_goTypes = []interface{}{
	(*DataBundle)(nil), // 0: eganow.api.billpay.DataBundle
}
var file_eganow_api_billpay_data_purchase_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eganow_api_billpay_data_purchase_entity_proto_init() }
func file_eganow_api_billpay_data_purchase_entity_proto_init() {
	if File_eganow_api_billpay_data_purchase_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eganow_api_billpay_data_purchase_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eganow_api_billpay_data_purchase_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eganow_api_billpay_data_purchase_entity_proto_goTypes,
		DependencyIndexes: file_eganow_api_billpay_data_purchase_entity_proto_depIdxs,
		MessageInfos:      file_eganow_api_billpay_data_purchase_entity_proto_msgTypes,
	}.Build()
	File_eganow_api_billpay_data_purchase_entity_proto = out.File
	file_eganow_api_billpay_data_purchase_entity_proto_rawDesc = nil
	file_eganow_api_billpay_data_purchase_entity_proto_goTypes = nil
	file_eganow_api_billpay_data_purchase_entity_proto_depIdxs = nil
}
