// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: eganow/api/gateway/developer_api/core_api_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoreEgaPayDeveloperApiSvc_GetAccessToken_FullMethodName           = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/GetAccessToken"
	CoreEgaPayDeveloperApiSvc_GetAccountHolderInfo_FullMethodName     = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/GetAccountHolderInfo"
	CoreEgaPayDeveloperApiSvc_GetCollectionServiceList_FullMethodName = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/GetCollectionServiceList"
	CoreEgaPayDeveloperApiSvc_GetPayoutServiceList_FullMethodName     = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/GetPayoutServiceList"
	CoreEgaPayDeveloperApiSvc_PayoutCreditAccount_FullMethodName      = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/PayoutCreditAccount"
	CoreEgaPayDeveloperApiSvc_CollectionDebitAccount_FullMethodName   = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/CollectionDebitAccount"
	CoreEgaPayDeveloperApiSvc_TransactionStatusQuery_FullMethodName   = "/eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc/TransactionStatusQuery"
)

// CoreEgaPayDeveloperApiSvcClient is the client API for CoreEgaPayDeveloperApiSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreEgaPayDeveloperApiSvcClient interface {
	GetAccessToken(ctx context.Context, in *CoreEgaPayDeveloperApiEmpty, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	GetAccountHolderInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error)
	GetCollectionServiceList(ctx context.Context, in *GetServiceListRequest, opts ...grpc.CallOption) (*GetServiceListResponse, error)
	GetPayoutServiceList(ctx context.Context, in *GetServiceListRequest, opts ...grpc.CallOption) (*GetServiceListResponse, error)
	PayoutCreditAccount(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	CollectionDebitAccount(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	TransactionStatusQuery(ctx context.Context, in *QueryTransferStatusRequest, opts ...grpc.CallOption) (*QueryTransferStatusTransferResponse, error)
}

type coreEgaPayDeveloperApiSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreEgaPayDeveloperApiSvcClient(cc grpc.ClientConnInterface) CoreEgaPayDeveloperApiSvcClient {
	return &coreEgaPayDeveloperApiSvcClient{cc}
}

func (c *coreEgaPayDeveloperApiSvcClient) GetAccessToken(ctx context.Context, in *CoreEgaPayDeveloperApiEmpty, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_GetAccessToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEgaPayDeveloperApiSvcClient) GetAccountHolderInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error) {
	out := new(GetAccountInfoResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_GetAccountHolderInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEgaPayDeveloperApiSvcClient) GetCollectionServiceList(ctx context.Context, in *GetServiceListRequest, opts ...grpc.CallOption) (*GetServiceListResponse, error) {
	out := new(GetServiceListResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_GetCollectionServiceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEgaPayDeveloperApiSvcClient) GetPayoutServiceList(ctx context.Context, in *GetServiceListRequest, opts ...grpc.CallOption) (*GetServiceListResponse, error) {
	out := new(GetServiceListResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_GetPayoutServiceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEgaPayDeveloperApiSvcClient) PayoutCreditAccount(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_PayoutCreditAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEgaPayDeveloperApiSvcClient) CollectionDebitAccount(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_CollectionDebitAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEgaPayDeveloperApiSvcClient) TransactionStatusQuery(ctx context.Context, in *QueryTransferStatusRequest, opts ...grpc.CallOption) (*QueryTransferStatusTransferResponse, error) {
	out := new(QueryTransferStatusTransferResponse)
	err := c.cc.Invoke(ctx, CoreEgaPayDeveloperApiSvc_TransactionStatusQuery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreEgaPayDeveloperApiSvcServer is the server API for CoreEgaPayDeveloperApiSvc service.
// All implementations must embed UnimplementedCoreEgaPayDeveloperApiSvcServer
// for forward compatibility
type CoreEgaPayDeveloperApiSvcServer interface {
	GetAccessToken(context.Context, *CoreEgaPayDeveloperApiEmpty) (*AccessTokenResponse, error)
	GetAccountHolderInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error)
	GetCollectionServiceList(context.Context, *GetServiceListRequest) (*GetServiceListResponse, error)
	GetPayoutServiceList(context.Context, *GetServiceListRequest) (*GetServiceListResponse, error)
	PayoutCreditAccount(context.Context, *TransferRequest) (*TransferResponse, error)
	CollectionDebitAccount(context.Context, *TransferRequest) (*TransferResponse, error)
	TransactionStatusQuery(context.Context, *QueryTransferStatusRequest) (*QueryTransferStatusTransferResponse, error)
	mustEmbedUnimplementedCoreEgaPayDeveloperApiSvcServer()
}

// UnimplementedCoreEgaPayDeveloperApiSvcServer must be embedded to have forward compatible implementations.
type UnimplementedCoreEgaPayDeveloperApiSvcServer struct {
}

func (UnimplementedCoreEgaPayDeveloperApiSvcServer) GetAccessToken(context.Context, *CoreEgaPayDeveloperApiEmpty) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) GetAccountHolderInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountHolderInfo not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) GetCollectionServiceList(context.Context, *GetServiceListRequest) (*GetServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionServiceList not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) GetPayoutServiceList(context.Context, *GetServiceListRequest) (*GetServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayoutServiceList not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) PayoutCreditAccount(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayoutCreditAccount not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) CollectionDebitAccount(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectionDebitAccount not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) TransactionStatusQuery(context.Context, *QueryTransferStatusRequest) (*QueryTransferStatusTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransactionStatusQuery not implemented")
}
func (UnimplementedCoreEgaPayDeveloperApiSvcServer) mustEmbedUnimplementedCoreEgaPayDeveloperApiSvcServer() {
}

// UnsafeCoreEgaPayDeveloperApiSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreEgaPayDeveloperApiSvcServer will
// result in compilation errors.
type UnsafeCoreEgaPayDeveloperApiSvcServer interface {
	mustEmbedUnimplementedCoreEgaPayDeveloperApiSvcServer()
}

func RegisterCoreEgaPayDeveloperApiSvcServer(s grpc.ServiceRegistrar, srv CoreEgaPayDeveloperApiSvcServer) {
	s.RegisterService(&CoreEgaPayDeveloperApiSvc_ServiceDesc, srv)
}

func _CoreEgaPayDeveloperApiSvc_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreEgaPayDeveloperApiEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_GetAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetAccessToken(ctx, req.(*CoreEgaPayDeveloperApiEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEgaPayDeveloperApiSvc_GetAccountHolderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetAccountHolderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_GetAccountHolderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetAccountHolderInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEgaPayDeveloperApiSvc_GetCollectionServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetCollectionServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_GetCollectionServiceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetCollectionServiceList(ctx, req.(*GetServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEgaPayDeveloperApiSvc_GetPayoutServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetPayoutServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_GetPayoutServiceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).GetPayoutServiceList(ctx, req.(*GetServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEgaPayDeveloperApiSvc_PayoutCreditAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).PayoutCreditAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_PayoutCreditAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).PayoutCreditAccount(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEgaPayDeveloperApiSvc_CollectionDebitAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).CollectionDebitAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_CollectionDebitAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).CollectionDebitAccount(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEgaPayDeveloperApiSvc_TransactionStatusQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEgaPayDeveloperApiSvcServer).TransactionStatusQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEgaPayDeveloperApiSvc_TransactionStatusQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEgaPayDeveloperApiSvcServer).TransactionStatusQuery(ctx, req.(*QueryTransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreEgaPayDeveloperApiSvc_ServiceDesc is the grpc.ServiceDesc for CoreEgaPayDeveloperApiSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreEgaPayDeveloperApiSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eganow.api.gateway.developer_api.CoreEgaPayDeveloperApiSvc",
	HandlerType: (*CoreEgaPayDeveloperApiSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessToken",
			Handler:    _CoreEgaPayDeveloperApiSvc_GetAccessToken_Handler,
		},
		{
			MethodName: "GetAccountHolderInfo",
			Handler:    _CoreEgaPayDeveloperApiSvc_GetAccountHolderInfo_Handler,
		},
		{
			MethodName: "GetCollectionServiceList",
			Handler:    _CoreEgaPayDeveloperApiSvc_GetCollectionServiceList_Handler,
		},
		{
			MethodName: "GetPayoutServiceList",
			Handler:    _CoreEgaPayDeveloperApiSvc_GetPayoutServiceList_Handler,
		},
		{
			MethodName: "PayoutCreditAccount",
			Handler:    _CoreEgaPayDeveloperApiSvc_PayoutCreditAccount_Handler,
		},
		{
			MethodName: "CollectionDebitAccount",
			Handler:    _CoreEgaPayDeveloperApiSvc_CollectionDebitAccount_Handler,
		},
		{
			MethodName: "TransactionStatusQuery",
			Handler:    _CoreEgaPayDeveloperApiSvc_TransactionStatusQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eganow/api/gateway/developer_api/core_api_service.proto",
}
