// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: eganow/api/gateway/eganow_app/money_transfer_entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EganowAppGatewayBankRequestType int32

const (
	EganowAppGatewayBankRequestType_BANK_REQ_UNSPECIFIED EganowAppGatewayBankRequestType = 0
	EganowAppGatewayBankRequestType_BANK_REQ_DEBIT       EganowAppGatewayBankRequestType = 1
	EganowAppGatewayBankRequestType_BANK_REQ_CREDIT      EganowAppGatewayBankRequestType = 2
)

// Enum value maps for EganowAppGatewayBankRequestType.
var (
	EganowAppGatewayBankRequestType_name = map[int32]string{
		0: "BANK_REQ_UNSPECIFIED",
		1: "BANK_REQ_DEBIT",
		2: "BANK_REQ_CREDIT",
	}
	EganowAppGatewayBankRequestType_value = map[string]int32{
		"BANK_REQ_UNSPECIFIED": 0,
		"BANK_REQ_DEBIT":       1,
		"BANK_REQ_CREDIT":      2,
	}
)

func (x EganowAppGatewayBankRequestType) Enum() *EganowAppGatewayBankRequestType {
	p := new(EganowAppGatewayBankRequestType)
	*p = x
	return p
}

func (x EganowAppGatewayBankRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EganowAppGatewayBankRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_enumTypes[0].Descriptor()
}

func (EganowAppGatewayBankRequestType) Type() protoreflect.EnumType {
	return &file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_enumTypes[0]
}

func (x EganowAppGatewayBankRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EganowAppGatewayBankRequestType.Descriptor instead.
func (EganowAppGatewayBankRequestType) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescGZIP(), []int{0}
}

var File_eganow_api_gateway_eganow_app_money_transfer_entity_proto protoreflect.FileDescriptor

var file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDesc = []byte{
	0x0a, 0x39, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2f, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x5f, 0x61, 0x70, 0x70, 0x2f,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x65, 0x67, 0x61,
	0x6e, 0x6f, 0x77, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x5f, 0x61, 0x70, 0x70, 0x2a, 0x64, 0x0a, 0x1f, 0x45, 0x67,
	0x61, 0x6e, 0x6f, 0x77, 0x41, 0x70, 0x70, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x42, 0x61,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x14, 0x42, 0x41, 0x4e, 0x4b, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x41, 0x4e, 0x4b, 0x5f,
	0x52, 0x45, 0x51, 0x5f, 0x44, 0x45, 0x42, 0x49, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x42,
	0x41, 0x4e, 0x4b, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x10, 0x02,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescOnce sync.Once
	file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescData = file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDesc
)

func file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescGZIP() []byte {
	file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescOnce.Do(func() {
		file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescData)
	})
	return file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDescData
}

var file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_goTypes = []interface{}{
	(EganowAppGatewayBankRequestType)(0), // 0: eganow.api.gateway.eganow_app.EganowAppGatewayBankRequestType
}
var file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_init() }
func file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_init() {
	if File_eganow_api_gateway_eganow_app_money_transfer_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_goTypes,
		DependencyIndexes: file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_depIdxs,
		EnumInfos:         file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_enumTypes,
	}.Build()
	File_eganow_api_gateway_eganow_app_money_transfer_entity_proto = out.File
	file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_rawDesc = nil
	file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_goTypes = nil
	file_eganow_api_gateway_eganow_app_money_transfer_entity_proto_depIdxs = nil
}
