// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: eganow/api/identity/identity_service.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_QoreIdentitySvc_QoreIdCallback_0(ctx context.Context, marshaler runtime.Marshaler, client QoreIdentitySvcClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq QoreIdCallbackRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.QoreIdCallback(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_QoreIdentitySvc_QoreIdCallback_0(ctx context.Context, marshaler runtime.Marshaler, server QoreIdentitySvcServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq QoreIdCallbackRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.QoreIdCallback(ctx, &protoReq)
	return msg, metadata, err

}

func request_NiaIdentitySvc_NiaIdentityData_0(ctx context.Context, marshaler runtime.Marshaler, client NiaIdentitySvcClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq NiaRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.NiaIdentityData(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_NiaIdentitySvc_NiaIdentityData_0(ctx context.Context, marshaler runtime.Marshaler, server NiaIdentitySvcServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq NiaRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.NiaIdentityData(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterQoreIdentitySvcHandlerServer registers the http handlers for service QoreIdentitySvc to "mux".
// UnaryRPC     :call QoreIdentitySvcServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterQoreIdentitySvcHandlerFromEndpoint instead.
func RegisterQoreIdentitySvcHandlerServer(ctx context.Context, mux *runtime.ServeMux, server QoreIdentitySvcServer) error {

	mux.Handle("POST", pattern_QoreIdentitySvc_QoreIdCallback_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/eganow.api.identity.QoreIdentitySvc/QoreIdCallback", runtime.WithHTTPPathPattern("/api/v1/qoreid/callback"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_QoreIdentitySvc_QoreIdCallback_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_QoreIdentitySvc_QoreIdCallback_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterNiaIdentitySvcHandlerServer registers the http handlers for service NiaIdentitySvc to "mux".
// UnaryRPC     :call NiaIdentitySvcServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterNiaIdentitySvcHandlerFromEndpoint instead.
func RegisterNiaIdentitySvcHandlerServer(ctx context.Context, mux *runtime.ServeMux, server NiaIdentitySvcServer) error {

	mux.Handle("POST", pattern_NiaIdentitySvc_NiaIdentityData_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/eganow.api.identity.NiaIdentitySvc/NiaIdentityData", runtime.WithHTTPPathPattern("/api/v1/nia"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_NiaIdentitySvc_NiaIdentityData_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_NiaIdentitySvc_NiaIdentityData_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterQoreIdentitySvcHandlerFromEndpoint is same as RegisterQoreIdentitySvcHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterQoreIdentitySvcHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterQoreIdentitySvcHandler(ctx, mux, conn)
}

// RegisterQoreIdentitySvcHandler registers the http handlers for service QoreIdentitySvc to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterQoreIdentitySvcHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterQoreIdentitySvcHandlerClient(ctx, mux, NewQoreIdentitySvcClient(conn))
}

// RegisterQoreIdentitySvcHandlerClient registers the http handlers for service QoreIdentitySvc
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "QoreIdentitySvcClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "QoreIdentitySvcClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "QoreIdentitySvcClient" to call the correct interceptors.
func RegisterQoreIdentitySvcHandlerClient(ctx context.Context, mux *runtime.ServeMux, client QoreIdentitySvcClient) error {

	mux.Handle("POST", pattern_QoreIdentitySvc_QoreIdCallback_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/eganow.api.identity.QoreIdentitySvc/QoreIdCallback", runtime.WithHTTPPathPattern("/api/v1/qoreid/callback"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_QoreIdentitySvc_QoreIdCallback_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_QoreIdentitySvc_QoreIdCallback_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_QoreIdentitySvc_QoreIdCallback_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"api", "v1", "qoreid", "callback"}, ""))
)

var (
	forward_QoreIdentitySvc_QoreIdCallback_0 = runtime.ForwardResponseMessage
)

// RegisterNiaIdentitySvcHandlerFromEndpoint is same as RegisterNiaIdentitySvcHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterNiaIdentitySvcHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterNiaIdentitySvcHandler(ctx, mux, conn)
}

// RegisterNiaIdentitySvcHandler registers the http handlers for service NiaIdentitySvc to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterNiaIdentitySvcHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterNiaIdentitySvcHandlerClient(ctx, mux, NewNiaIdentitySvcClient(conn))
}

// RegisterNiaIdentitySvcHandlerClient registers the http handlers for service NiaIdentitySvc
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "NiaIdentitySvcClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "NiaIdentitySvcClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "NiaIdentitySvcClient" to call the correct interceptors.
func RegisterNiaIdentitySvcHandlerClient(ctx context.Context, mux *runtime.ServeMux, client NiaIdentitySvcClient) error {

	mux.Handle("POST", pattern_NiaIdentitySvc_NiaIdentityData_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/eganow.api.identity.NiaIdentitySvc/NiaIdentityData", runtime.WithHTTPPathPattern("/api/v1/nia"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_NiaIdentitySvc_NiaIdentityData_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_NiaIdentitySvc_NiaIdentityData_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_NiaIdentitySvc_NiaIdentityData_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "v1", "nia"}, ""))
)

var (
	forward_NiaIdentitySvc_NiaIdentityData_0 = runtime.ForwardResponseMessage
)
